#!/bin/sh
# Generated by tools/bootstrap.nio. Do not edit.
#
# Builds the nio compiler from the checked-in IR with clang only. This is
# stage 0: it needs no nio, only a C toolchain and this repository. After
# it, the compiler builds itself.
#
#	bootstrap/build.sh [output]        (default: ./nio; a .exe under a Windows shell)
#
# The C files are the ones the compiler's imports need. The compile that
# emitted nio.ll lists them (tools/bootstrap.nio).
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out=${1:-nio}
# The Windows linker writes the time into the header. Brepro stops that,
# so two builds give the same file. The linker also accepts the option with
# a dash, and that form stops the shell from reading it as a path.
repro=
case $(uname -s) in
MINGW*|MSYS*|CYGWIN*)
    case $out in *.exe) ;; *) out=$out.exe ;; esac
    repro=-Wl,-Brepro
    libs="-lbcrypt -lws2_32"
    ;;
*)
    libs=""
    ;;
esac
rt="$root/build/runtime"

set -- -O2 ${repro:+$repro} -I "$rt" -o "$out" "$root/bootstrap/nio.ll" \
    "$rt/runtime.c" \
    "$rt/gc.c" \
    "$rt/lib/map.c" \
    "$rt/lib/string.c" \
    "$rt/lib/array.c" \
    "$rt/lib/fs.c" \
    "$rt/lib/path.c" \
    "$rt/lib/crypto.c" \
    "$rt/lib/os.c" \
    "$rt/lib/process.c" \
    "$rt/lib/json.c" \
    "$rt/lib/time.c" \
    "$rt/lib/net.c" \
    "$rt/lib/async.c" \
    "$rt/lib/regexp.c"

# The libraries the built-in modules need, chosen per host above. They come
# last, because a linker that resolves left to right ignores a library named
# before the object that uses it. They are unquoted, so an empty set adds
# nothing.
# shellcheck disable=SC2086
set -- "$@" $libs

# -flto lets clang inline the runtime into the generated code, and needs a
# linker that reads bitcode. Apple's ld64 and LLVM's lld do. GNU ld does only
# with the plugin installed. A failure retries without it, as the compiler's
# own link does, so the flag stays an optimization.
clang -flto "$@" 2>/dev/null || clang "$@"

echo "built $out"
